version: 2
jobs:
  job1:
    branches:
      only: 
        - main
      ignore:
        - develop
    docker:
      - image: circleci/node:12.0
    working_directory: ~/repo
    environment:
      NODE_ENV: test
    steps:
      - run: node --version; npm --version
      - checkout
      - run:
          name: Log versions
          command: |
            echo "bash: $(bash --version)"
            echo "git: $(git --version)"
            echo "node: $(node --version)"
            echo "npm: $(npm --version)"
