version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.0
    working_directory: ~/repo
    environment:
      NODE_ENV: test
    steps:
      - run: node --version; npm --version
      - checkout
      - run:
          name: Log versions
          command: |
            echo "bash: $(bash --version)"
            echo "git: $(git --version)"
            echo "node: $(node --version)"
            echo "npm: $(npm --version)"
      - restore_cache:
          name: Restore npm cache
          key: dependency-cache-{{checksum "package.json"}}

      - run:
          name: Install packages
          command: npm ci
      - run:
          name: 'Build Project'
          command: 'npm run build'

  deploy:
    branches:
      only: 
        - main
      ignore:
        - branch1
    docker:
      - image: circleci/node:12.0
    working_directory: ~/repo
    environment:
      NODE_ENV: test
    steps:
      - checkout
      - run:
          name: 'Deploy to Firebase Hosting..'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
